# This is a basic workflow to help you get started with Actions

name: Basic test MocoLoco

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install dep for compilation and gsl
        run: sudo apt install build-essential libgsl-dev

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: g++ -o MOCO -Wall $GITHUB_WORKSPACE/MocoLoco.cpp  -lgsl -lgslcblas -O3

      - name: SS test 
        run: ./MOCO -m Test_Bed/random_fasta.fasta -k 6 -d 1 -f 0.01 -ss
      
      - name: get kmer test
        run: wget https://gist.githubusercontent.com/AmarettiL/0cba8a28f012ef6136fefe685a31b7af/raw/6df414f5cc836bc78a12d73f9a18df5e2624ab87/SS_fasta.txt

      - name: test difference between outputs
        run: diff SS_fasta.txt 6-mers_Z_scores_fasta_SS.txt

      - name: Multifasta test 
        run: ./MOCO -m Test_Bed/random_fasta.fasta -k 6 -d 1 -f 0.01
      
      - name: get kmer test
        run: wget https://gist.githubusercontent.com/AmarettiL/f660d251c1afafad74ac0c4e6b293508/raw/bf7f92bc8f793eaf5a9781c5ca20e2c5614ea45b/6_mers_fasta2.txt
      
      - name: test difference between outputs
        run: diff 6_mers_fasta2.txt 6-mers_Z_scores_fasta_DS.txt
      
      - name: hg19 genome download 
        run: cat get_hg19.script | bash
        working-directory: Genomes/hg19

      - name: Run NFY test
        run: ./MOCO -b Test_Bed/nfy_k562_hg19.bed -j Jaspar_2020/MA0060.1.jaspar -t Genomes/hg19/hg19.2bit -p 150 -k 6 -d 1 -f 0.01
          
      - name: get sample test 
        run: wget https://gist.githubusercontent.com/AmarettiL/9db7479a3d423dc7dbc814e619e81990/raw/3a42a630eaff55250243661a2c5b4e5f08966cf1/NFY_simple_test.txt

      - name: test difference between outputs 
        run: diff NFY_simple_test.txt 6-mers_Z_scores_hg19.2bit_MA0060.1.jaspar_nfy_k562_hg19.bedDS.txt

      - name: Run unidirection test (with -o)
        run: ./MOCO -b Test_Bed/nfy_k562_hg19.bed -j Jaspar_2020/MA0060.1.jaspar -t Genomes/hg19/hg19.2bit -p 150 -k 6,8 -d 1,2 -f 0.01,0.01 -o p -e c -u
          
      - name: get sample test 
        run: |
              wget https://gist.githubusercontent.com/AmarettiL/f26fa0b9a1fa3c4d4e7f01d49185a8db/raw/c558fd5c2517a0fbe2885d3c5cdc98eb5fecbf9f/6_mers_NFY_all.txt && \
              wget https://gist.githubusercontent.com/AmarettiL/95e27df230243e33a9da1ea80f94dc4a/raw/e930c4a5270c5cac7de2740a7384025eb8e6d552/8_mers_NFY_all.txt
      
      - name: test difference between outputs 
        run: |
              diff 6_mers_NFY_all.txt 6-mers_Z_scores_hg19.2bit_MA0060.1.jaspar_nfy_k562_hg19.bedDS.txt && \
              diff 8_mers_NFY_all.txt 8-mers_Z_scores_hg19.2bit_MA0060.1.jaspar_nfy_k562_hg19.bedDS.txt
